#!/usr/bin/env bash
# Build this checkout and install it side by side with the released binaries.
#
# Usage:
#   scripts/install-dev.sh              build and install ws-dev, workspace-status-dev,
#                                       and workspace-status-update-dev
#   scripts/install-dev.sh --uninstall  remove only those three -dev names
#   scripts/install-dev.sh -h | --help  print this help
#
# Environment:
#   WS_DEV_BIN_DIR     install directory (default: $HOME/.local/bin)
#   WS_DEV_TARGET_DIR  cargo target dir (default: <repo>/target/dev-install)
#   CARGO_BUILD_JOBS   respected when exported by the caller
#
# The build sets WS_STATUS_DEV_BUILD to the short git sha (+ "-dirty"), so
# `ws-dev --version` shows it, the TUI skips the release update prompt, and
# `ws-dev --update` runs workspace-status-update-dev, which re-runs this script.
# The released ws, workspace-status, and workspace-status-update are never
# written or removed.
set -euo pipefail

script_path=$(readlink -f -- "${BASH_SOURCE[0]}")
repo_root=$(cd -- "$(dirname -- "$script_path")/.." && pwd -P)
bin_dir="${WS_DEV_BIN_DIR:-$HOME/.local/bin}"
target_dir="${WS_DEV_TARGET_DIR:-$repo_root/target/dev-install}"

# Every name this script writes or removes. Each must end in -dev. The
# *-update-dev name is the update shim; every other name installs the release
# binary of the same name without -dev.
readonly DEV_NAMES=(ws-dev workspace-status-dev workspace-status-update-dev)

usage() {
  sed -n '2,/^set -euo pipefail$/p' "$script_path" | sed -e '$d' -e 's/^# \{0,1\}//'
}

guard_dev_names() {
  local name
  for name in "${DEV_NAMES[@]}"; do
    if [[ "$name" != *-dev ]]; then
      echo "install-dev.sh: refusing non-dev target name: $name" >&2
      exit 1
    fi
  done
}

uninstall() {
  local name
  for name in "${DEV_NAMES[@]}"; do
    rm -f -- "${bin_dir:?}/$name"
  done
  echo "Removed ${DEV_NAMES[*]} from $bin_dir. Released ws is untouched."
}

dev_marker() {
  local sha
  sha=$(git -C "$repo_root" rev-parse --short HEAD)
  if [[ -n "$(git -C "$repo_root" status --porcelain)" ]]; then
    sha="${sha}-dirty"
  fi
  printf '%s\n' "$sha"
}

install_dev() {
  local marker
  marker=$(dev_marker)
  echo "Building workspace-status (dev ${marker}) into ${target_dir}..."
  (
    cd -- "$repo_root"
    WS_STATUS_DEV_BUILD="$marker" CARGO_TARGET_DIR="$target_dir" \
      cargo build --release --locked -p workspace-status
  )

  mkdir -p -- "$bin_dir"
  local shim_tmp
  shim_tmp=$(mktemp)
  cat >"$shim_tmp" <<EOF
#!/usr/bin/env bash
# Generated by $script_path. Rebuilds and reinstalls that checkout.
export WS_DEV_BIN_DIR=\${WS_DEV_BIN_DIR:-$(printf '%q' "$bin_dir")}
export WS_DEV_TARGET_DIR=\${WS_DEV_TARGET_DIR:-$(printf '%q' "$target_dir")}
exec $(printf '%q' "$script_path") "\$@"
EOF
  # Every destination comes from DEV_NAMES, so guard_dev_names covers it.
  local name
  for name in "${DEV_NAMES[@]}"; do
    case "$name" in
      *-update-dev) install -m 0755 -- "$shim_tmp" "$bin_dir/$name" ;;
      *) install -m 0755 -- "$target_dir/release/${name%-dev}" "$bin_dir/$name" ;;
    esac
  done
  rm -f -- "$shim_tmp"

  echo
  echo "Installed:"
  for name in "${DEV_NAMES[@]}"; do
    echo "  $bin_dir/$name"
  done
  echo
  "$bin_dir/${DEV_NAMES[0]}" --version
  echo
  echo "Run 'hash -r' if your shell cached an old path. Released ws is untouched."
}

guard_dev_names
case "${1:-}" in
  -h | --help) usage ;;
  --uninstall) uninstall ;;
  "") install_dev ;;
  *)
    echo "install-dev.sh: unknown argument: $1" >&2
    usage >&2
    exit 2
    ;;
esac
